name: Selenium Google Finance Test Suite

on:
  # schedule:
  #   # Run every day at midnight (UTC)
  #   - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      run_type:
        type: choice
        description: "Select the tests to run"
        required: true
        default: "all"
        options:
          - all
          - specific

      specific_tests:
        description: |
          Comma-separated list of specific tests to run (if applicable)
          i.e. test_stock_symbols_in_both_given_data_and_finance_page, test_stock_symbols_in_finance_page_not_in_given_data
        required: false # Make it optional
        default: "" # Set an empty default value if none is provided

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run Selenium Tests
        run: |
          if [ "${{ github.event.inputs.run_type }}" == "specific" ]; then
            tests="${{ github.event.inputs.specific_tests }}"
            if [ -z "$tests" ]; then
              echo "No specific tests provided, running all tests instead."
              pytest
            else
              IFS=',' read -r -a test_array <<< "$tests"
              for test in "${test_array[@]}"; do
                pytest -vvv -k "$test"
              done
            fi
          else
            pytest -vvv
          fi
