name: Selenium Google Finance Test Suite

on:
  schedule:
    # Run every day at midnight (UTC)
    - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      run_type:
        description: "Select the type of tests to run"
        required: true
        default: ""

      specific_tests:
        description: "Comma-separated list of specific tests to run (if applicable)"
        required: false # Make it optional
        default: "" # Set an empty default value if none is provided

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run Selenium Tests
        run: |
          if [ "${{ github.event.inputs.run_type }}" == "specific" ]; then
            tests="${{ github.event.inputs.specific_tests }}"
            if [ -z "$tests" ]; then
              echo "No specific tests provided, running all tests instead."
              pytest
            else
              IFS=',' read -r -a test_array <<< "$tests"
              for test in "${test_array[@]}"; do
                pytest -vvv "$test"
              done
            fi
          else
            pytest
          fi
